### ISSUE TITLE
Update results in blank page

### ISSUE THREAD

**Issue by virk** [Juergen-aus-Zuendorf/dokuwiki-plugin-footer#2]
I just tried to update the footer plugin to version from yesterday and get a blank page. I tested this on two wikis.
1) Anybody else had this experience?
2) Is the version from earlier available somewhere? Otherwise I will restore it from backup. (6 minutes later: Okay, no more necessary: I replaced it from backup)

**Comment by Juergen-aus-Zuendorf** [comment]
Oh, sorry! I made a small correction, now it should work so far.

**Comment by virk** [comment]
Okay! That seems to have been successful. Thank you!
