### ISSUE TITLE
footer with farmer plugin: not visible

### ISSUE THREAD

**Issue by farmascript** [Juergen-aus-Zuendorf/dokuwiki-plugin-footer#3]
A footer is not showing when placed in the namespace of an 'animal' when using the 'farmer' plugin

**Comment by Juergen-aus-Zuendorf** [comment]
Did you purge the cache?

**Comment by farmascript** [comment]
yes. adding &purge=true to the url does not change anything.
When placed in the 'farmer' pages it acts ok.

**Comment by farmascript** [comment]
Sorry, my mistake. 
When an animal is created, it inhereted the 'hf' and 'hfu' prefixes from the farmer. Emptying them in the configuration file of the animal make it work ok.
Sorry again.

**Comment by Juergen-aus-Zuendorf** [comment]
No problem! 
Thank you for your hint
